syntax = "proto3";

package gamepb.interactpb;

message InteractRecord {
    int64 server_time = 1;
    int32 action_type = 2;
    int64 visitor_gid = 3;
    string nick = 4;
    string avatar_url = 5;
    int32 crop_id = 6;
    int32 crop_count = 7;
    int32 times = 8;
    int32 from_type = 9;
    int32 level = 10;

    message Extra {
        int32 land_id = 1;
        int32 flag1 = 2;
        int32 flag2 = 3;
    }

    Extra extra = 11;
}

message InteractRecordsRequest {}

message InteractRecordsReply {
    repeated InteractRecord records = 1;
}

message GetInteractInfoRequest {}

message GetInteractInfoReply {
    bool has_reward = 1;
    int64 next_reset_at = 2;
}
