export interface GameOperationSpec {
  service: string
  method: string
}

export const GAME_OPERATION_CATALOG = {
  'farm.allLands': { service: 'gamepb.plantpb.PlantService', method: 'AllLands' },
  'farm.harvest': { service: 'gamepb.plantpb.PlantService', method: 'Harvest' },
  'farm.waterLand': { service: 'gamepb.plantpb.PlantService', method: 'WaterLand' },
  'farm.weedOut': { service: 'gamepb.plantpb.PlantService', method: 'WeedOut' },
  'farm.insecticide': { service: 'gamepb.plantpb.PlantService', method: 'Insecticide' },
  'farm.fertilize': { service: 'gamepb.plantpb.PlantService', method: 'Fertilize' },
  'farm.removePlant': { service: 'gamepb.plantpb.PlantService', method: 'RemovePlant' },
  'farm.upgradeLand': { service: 'gamepb.plantpb.PlantService', method: 'UpgradeLand' },
  'farm.unlockLand': { service: 'gamepb.plantpb.PlantService', method: 'UnlockLand' },
  'farm.plant': { service: 'gamepb.plantpb.PlantService', method: 'Plant' },
  'shop.shopInfo': { service: 'gamepb.shoppb.ShopService', method: 'ShopInfo' },
  'shop.buyGoods': { service: 'gamepb.shoppb.ShopService', method: 'BuyGoods' },
  'task.taskInfo': { service: 'gamepb.taskpb.TaskService', method: 'TaskInfo' },
  'task.claimTaskReward': { service: 'gamepb.taskpb.TaskService', method: 'ClaimTaskReward' },
  'task.claimDailyReward': { service: 'gamepb.taskpb.TaskService', method: 'ClaimDailyReward' },
  'illustrated.claimAllRewardsV2': { service: 'gamepb.illustratedpb.IllustratedService', method: 'ClaimAllRewardsV2' },
  'illustrated.getIllustratedListV2': { service: 'gamepb.illustratedpb.IllustratedService', method: 'GetIllustratedListV2' },
  'daily.email.getEmailList': { service: 'gamepb.emailpb.EmailService', method: 'GetEmailList' },
  'daily.email.batchClaimEmail': { service: 'gamepb.emailpb.EmailService', method: 'BatchClaimEmail' },
  'daily.email.claimEmail': { service: 'gamepb.emailpb.EmailService', method: 'ClaimEmail' },
  'daily.mall.getMonthCardInfos': { service: 'gamepb.mallpb.MallService', method: 'GetMonthCardInfos' },
  'daily.mall.claimMonthCardReward': { service: 'gamepb.mallpb.MallService', method: 'ClaimMonthCardReward' },
  'daily.mall.getMallListBySlotType': { service: 'gamepb.mallpb.MallService', method: 'GetMallListBySlotType' },
  'daily.mall.purchase': { service: 'gamepb.mallpb.MallService', method: 'Purchase' },
  'daily.redpacket.getTodayClaimStatus': { service: 'gamepb.redpacketpb.RedPacketService', method: 'GetTodayClaimStatus' },
  'daily.redpacket.claimRedPacket': { service: 'gamepb.redpacketpb.RedPacketService', method: 'ClaimRedPacket' },
  'daily.qqvip.getDailyGiftStatus': { service: 'gamepb.qqvippb.QQVipService', method: 'GetDailyGiftStatus' },
  'daily.qqvip.claimDailyGift': { service: 'gamepb.qqvippb.QQVipService', method: 'ClaimDailyGift' },
  'daily.share.checkCanShare': { service: 'gamepb.sharepb.ShareService', method: 'CheckCanShare' },
  'daily.share.reportShare': { service: 'gamepb.sharepb.ShareService', method: 'ReportShare' },
  'daily.share.claimShareReward': { service: 'gamepb.sharepb.ShareService', method: 'ClaimShareReward' },
  'invite.reportArkClick': { service: 'gamepb.userpb.UserService', method: 'ReportArkClick' },
  'warehouse.bag': { service: 'gamepb.itempb.ItemService', method: 'Bag' },
  'warehouse.sell': { service: 'gamepb.itempb.ItemService', method: 'Sell' },
  'warehouse.use': { service: 'gamepb.itempb.ItemService', method: 'Use' },
  'warehouse.batchUse': { service: 'gamepb.itempb.ItemService', method: 'BatchUse' },
  'friend.syncAll': { service: 'gamepb.friendpb.FriendService', method: 'SyncAll' },
  'friend.getAll': { service: 'gamepb.friendpb.FriendService', method: 'GetAll' },
  'friend.getApplications': { service: 'gamepb.friendpb.FriendService', method: 'GetApplications' },
  'friend.acceptFriends': { service: 'gamepb.friendpb.FriendService', method: 'AcceptFriends' },
  'friend.enter': { service: 'gamepb.visitpb.VisitService', method: 'Enter' },
  'friend.leave': { service: 'gamepb.visitpb.VisitService', method: 'Leave' },
  'friend.checkCanOperate': { service: 'gamepb.plantpb.PlantService', method: 'CheckCanOperate' },
  'friend.interactRecords': { service: 'gamepb.interactpb.InteractService', method: 'InteractRecords' },
  'friend.getInteractRecords': { service: 'gamepb.interactpb.InteractService', method: 'GetInteractRecords' },
  'friend.visitorInteractRecords': { service: 'gamepb.interactpb.VisitorService', method: 'InteractRecords' },
  'friend.visitorGetInteractRecords': { service: 'gamepb.interactpb.VisitorService', method: 'GetInteractRecords' },
  'friend.harvest': { service: 'gamepb.plantpb.PlantService', method: 'Harvest' },
  'friend.putInsects': { service: 'gamepb.plantpb.PlantService', method: 'PutInsects' },
  'friend.putWeeds': { service: 'gamepb.plantpb.PlantService', method: 'PutWeeds' }
} as const satisfies Record<string, GameOperationSpec>

export type GameOperationKey = keyof typeof GAME_OPERATION_CATALOG
