import type { DevicePreset } from '@qq-farm/shared'

export const DEVICE_PRESETS: DevicePreset[] = [
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max (当前默认)',
    category: 'ios',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'qq',
      os: 'iOS',
      sysSoftware: 'iOS 26.3.1',
      sysHardware: 'iPhone16,2',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 1290,
      screenHeight: 2796,
      density: 3.0,
      cpu: 'arm64',
      memory: 8192,
      glRender: 'Apple GPU',
      glVersion: 'OpenGL ES 3.0',
      deviceId: 'iPhone16,2',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.54(0x18003631) NetType/WIFI Language/zh_CN',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    category: 'ios',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'qq',
      os: 'iOS',
      sysSoftware: 'iOS 17.6.1',
      sysHardware: 'iPhone15,2',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 1170,
      screenHeight: 2532,
      density: 3.0,
      cpu: 'arm64',
      memory: 6144,
      glRender: 'Apple GPU',
      glVersion: 'OpenGL ES 3.0',
      deviceId: 'iPhone15,2',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.53(0x18003530) NetType/WIFI Language/zh_CN',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  },
  {
    id: 'iphone-x-default',
    name: 'iPhone X',
    category: 'ios',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'qq',
      os: 'iOS',
      sysSoftware: 'iOS 16.7.10',
      sysHardware: 'iPhone10,3',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 1125,
      screenHeight: 2436,
      density: 3.0,
      cpu: 'arm64',
      memory: 3072,
      glRender: 'Apple GPU',
      glVersion: 'OpenGL ES 3.0',
      deviceId: 'iPhone X<iPhone10,3>',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_10 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.54(0x18003631) NetType/WIFI Language/zh_CN',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  },
  {
    id: 'xiaomi-14-pro',
    name: '小米 14 Pro',
    category: 'android',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'qq',
      os: 'android',
      sysSoftware: 'Android 14',
      sysHardware: 'Xiaomi 2311DRK48C',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 1440,
      screenHeight: 3200,
      density: 3.5,
      cpu: 'arm64-v8a',
      memory: 12288,
      glRender: 'Adreno (TM) 750',
      glVersion: 'OpenGL ES 3.2',
      deviceId: '',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; 2311DRK48C Build/UKQ1.230804.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.188 Mobile Safari/537.36 MicroMessenger/8.0.54.2800(0x2800363B) NetType/WIFI Language/zh_CN',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  },
  {
    id: 'samsung-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'android',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'qq',
      os: 'android',
      sysSoftware: 'Android 14',
      sysHardware: 'Samsung SM-S928B',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 1440,
      screenHeight: 3120,
      density: 3.0,
      cpu: 'arm64-v8a',
      memory: 12288,
      glRender: 'Adreno (TM) 750',
      glVersion: 'OpenGL ES 3.2',
      deviceId: '',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-S928B Build/UP1A.231005.007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.188 Mobile Safari/537.36 MicroMessenger/8.0.54.2800(0x2800363B) NetType/WIFI Language/zh_CN',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  },
  {
    id: 'windows-wechat',
    name: 'Windows 微信',
    category: 'windows',
    profile: {
      clientVersion: '1.7.0.6_20260313',
      platform: 'wx',
      os: 'iOS',
      sysSoftware: 'Windows Unknown x64',
      sysHardware: '',
      telecomOper: '',
      network: 'wifi',
      screenWidth: 0,
      screenHeight: 0,
      density: 0,
      cpu: 'microsoft',
      memory: 7672,
      glRender: '',
      glVersion: '',
      deviceId: '',
      androidOaid: '',
      iosCaid: '',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 MicroMessenger/7.0.20.1781(0x6700143B) NetType/WIFI MiniProgramEnv/Windows WindowsWechat/WMPF WindowsWechat(0x63090a13)',
      origin: 'https://gate-obt.nqf.qq.com'
    }
  }
]
